export const ftui = {
  version: '58.25.6-design-system-consolidation-app-ui-hardening',
  page: {
    frame: 'ft-page-frame',
    hero: 'ft-page-hero',
    panel: 'ft-panel',
    card: 'ft-card',
    subcard: 'ft-subcard',
    muted: 'ft-card-muted',
  },
  text: {
    kicker: 'ft-kicker',
    page: 'ft-heading-page',
    section: 'ft-heading-section',
    copy: 'ft-copy',
    main: 'ft-text-main',
    soft: 'ft-text-soft',
    muted: 'ft-text-muted',
    faint: 'ft-text-faint',
  },
  controls: {
    input: 'ft-input',
    inputLarge: 'ft-input-lg',
    textarea: 'ft-textarea',
    select: 'ft-select',
    switch: 'ft-switch',
    toggle: 'ft-toggle',
    checkbox: 'ft-checkbox',
    range: 'ft-range',
  },
  buttons: {
    base: 'ft-btn',
    primary: 'ft-btn ft-btn-md ft-btn-primary',
    secondary: 'ft-btn ft-btn-md ft-btn-secondary',
    ghost: 'ft-btn ft-btn-md ft-btn-ghost',
    danger: 'ft-btn ft-btn-md ft-btn-danger',
    icon: 'ft-btn ft-btn-icon ft-btn-secondary',
  },
  data: {
    metric: 'ft-metric-card',
    metricLabel: 'ft-metric-label',
    metricValue: 'ft-metric-value',
    chip: 'ft-chip',
    chipActive: 'ft-chip ft-chip-active',
    row: 'ft-row',
    listRow: 'ft-list-row',
    actionbar: 'ft-actionbar',
  },
  state: {
    dangerZone: 'ft-danger-zone',
    divider: 'ft-divider',
    nestedReset: 'ft-nested-card-reset',
  },
} as const;

export const flowtaskUiArchitecture = {
  goal: 'one architecture for pages, cards, controls, typography, actions and feedback',
  inspiration: ['Apple HIG hierarchy/harmony/consistency', 'Asana clarity and focus', 'Notion clean content-first density'],
  rules: [
    'Every page uses one page frame and one visual hierarchy.',
    'Cards use three sizes only: hero/panel, card, subcard.',
    'Controls share one input/select/textarea style and one focus ring.',
    'Checkboxes, switches and ranges are styled globally under ft-app-root.',
    'Buttons use one primary action per context and secondary/ghost for the rest.',
    'Motion communicates state only; no decorative jumps.',
  ],
} as const;
