"use client";

import Link from "next/link";
import { useEffect, useMemo, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, AlertCircle, Bell, CalendarDays, CheckCircle2, FileArchive, FileSpreadsheet, FileText, Flag, Folder, Image as ImageIcon, Paperclip, Plus, Share2, Sparkles, Trash2 } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import { EntityAttachments } from "@/components/attachments/entity-attachments";
import { safeDeleteTaskClient } from "@/lib/tasks/safe-delete-client";
import { TaskChecklistCard } from "@/components/tasks/task-checklist-card";
import { TaskOperationalFeed } from "@/components/tasks/task-operational-feed";
import { formatDate } from "@/lib/utils/dates";
import { logActivity } from "@/lib/activity/log-client";
import { getMutationErrorMessage } from "@/lib/supabase/mutation-confirmation";

type Props = { task: any; queryString?: string; comments: any[]; assignableUsers: any[]; assignees: any[]; attachments: any[]; activity: any[]; access: any; checklistItems: any[]; department?: any | null; project?: any | null; initialEdit?: boolean; taskIsOverdue?: boolean; standbyDays?: number; };
type DepartmentOption = { id: string; code?: string | null; name: string };
type FormState = { title: string; description: string; status: string; priority: string; dueDate: string; clientName: string; departmentId: string; };

const statusOptions = ["en_proceso", "produccion", "en_espera", "concluido"] as const;
const priorityOptions = ["alta", "media", "baja"] as const;

function buildInitialForm(task: any): FormState { return { title: task.title ?? "", description: task.description ?? "", status: statusOptions.includes(task.status) ? task.status : "en_proceso", priority: priorityOptions.includes(task.priority) ? task.priority : "media", dueDate: task.due_date ?? "", clientName: task.client_name ?? "", departmentId: task.department_id ? String(task.department_id) : "" }; }
function humanStatus(value?: string | null) { return ({ en_espera: "En espera", en_proceso: "En proceso", produccion: "Producción", concluido: "Concluida" } as Record<string,string>)[value || ""] || (value ? value.replaceAll("_", " ") : "Sin estado"); }
function priorityLabel(value?: string | null) { return value === "alta" ? "Alta" : value === "baja" ? "Baja" : "Media"; }
function initials(name?: string | null) { return (name || "FT").split(" ").filter(Boolean).slice(0, 2).map((part) => part[0]).join("").toUpperCase(); }
function actorName(item: any) { const raw = item?.actor_name || item?.actor?.full_name || item?.actor?.email || ""; return !raw || raw === "FlowTask" ? "Sistema" : raw; }
function activityLabel(item: any) { const action = item?.action; const metadata = item?.metadata || {}; if (action === "task_status_changed") return `${actorName(item)} cambió el estado a ${humanStatus(metadata.status)}`; if (action === "deadline_changed" && metadata.deadline) return `Fecha límite actualizada: ${formatDate(String(metadata.deadline))}`; if (action === "checklist_item_completed") return "Se completó un punto del checklist"; if (action === "checklist_item_reopened") return "Se reabrió un punto del checklist"; if (action === "checklist_item_added") return "Se agregó un punto al checklist"; if (action === "checklist_item_deleted") return "Se eliminó un punto del checklist"; if (action === "comment_added") return "Se agregó un comentario"; if (action === "file_uploaded" || action === "attachment_uploaded") return "Se subió un archivo"; if (action === "task_created") return "Se creó la tarea"; if (action === "task_updated") return "Se actualizó la tarea"; return `${actorName(item)} registró actividad`; }
function AttachmentPreviewIcon({ file }: { file: any }) {
  const name = String(file?.file_name || "").toLowerCase();
  const mime = String(file?.mime_type || "").toLowerCase();
  if (mime.startsWith("image/") || /\.(png|jpg|jpeg|webp|gif|svg)$/.test(name)) return <ImageIcon className="h-7 w-7" />;
  if (mime.includes("spreadsheet") || /\.(xlsx|xls|csv)$/.test(name)) return <FileSpreadsheet className="h-7 w-7 text-emerald-600" />;
  if (mime.includes("zip") || /\.(zip|rar|7z)$/.test(name)) return <FileArchive className="h-7 w-7 text-slate-600" />;
  return <FileText className="h-7 w-7 text-rose-600" />;
}
function ProgressInline({ value }: { value: number }) { return <span className="inline-flex min-w-[190px] items-center gap-3 text-sm font-bold text-[#334155]"><span>{value}% completado</span><span className="h-[5px] flex-1 rounded-full bg-[#E2E8F0]"><span className="block h-[5px] rounded-full bg-[#16C784] transition-all duration-500" style={{ width: `${value}%` }} /></span></span>; }
function SaveStateBadge({ state }: { state: "idle" | "saving" | "saved" | "error" }) { const label = state === "saving" ? "Guardando cambios…" : state === "error" ? "No se pudo guardar" : "Cambios guardados"; return <span className={`inline-flex items-center gap-2 text-sm font-semibold ${state === "error" ? "text-rose-600" : "ft-text-muted"}`}><CheckCircle2 className={`h-4 w-4 ${state === "saving" ? "ft-skeleton-line text-[#16C784]" : state === "error" ? "text-rose-500" : "text-[#16C784]"}`} />{label}</span>; }
function MetaChip({ children }: { children: React.ReactNode }) { return <span className="inline-flex h-9 items-center gap-2 rounded-full border border-[#E2E8F0] bg-white px-3 text-xs font-semibold text-[#475569]">{children}</span>; }
function SidePanel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-2xl border border-[#E2E8F0] bg-white p-5"><h3 className="text-base font-semibold ft-text-main">{title}</h3><div className="mt-5 space-y-4">{children}</div></section>; }
function InlineMeta({ label, children }: { label: string; children: React.ReactNode }) { return <div className="grid grid-cols-[110px_1fr] items-center gap-4 text-sm"><span className="font-bold ft-text-muted">{label}</span><div className="min-w-0 font-semibold ft-text-main">{children}</div></div>; }

export function TaskWorkspaceInline({ task, queryString = "", comments, assignableUsers, assignees, attachments, activity, access, checklistItems, department, project, initialEdit = false, taskIsOverdue = false, standbyDays = 0 }: Props) {
  const router = useRouter(); const supabase = useMemo(() => createClient(), []); const canEdit = Boolean(access?.canEdit || access?.isAssignee);
  const [localTask, setLocalTask] = useState<any>(task);
  const initialForm = useMemo(() => buildInitialForm(localTask), [localTask]);
  const [mode, setMode] = useState<"read" | "edit">(initialEdit && canEdit ? "edit" : "read"); const [saveState, setSaveState] = useState<"idle" | "saving" | "saved" | "error">("saved"); const [shareState, setShareState] = useState<"idle" | "copied" | "error">("idle"); const [form, setForm] = useState<FormState>(initialForm); const [departmentOptions, setDepartmentOptions] = useState<DepartmentOption[]>(department ? [{ id: String(department.id), code: department.code, name: department.name }] : []); const [notice, setNotice] = useState<{ tone: "success" | "error" | "info"; message: string } | null>(null); const [confirmDeleteOpen, setConfirmDeleteOpen] = useState(false); const [, startTransition] = useTransition();

  useEffect(() => {
    setLocalTask(task);
    setForm(buildInitialForm(task));
  }, [task]);

  useEffect(() => {
    let active = true;
    async function loadDepartments() {
      if (!canEdit) return;
      const { data, error } = await supabase
        .from("departments")
        .select("id,code,name,organization_id,account_owner_id")
        .limit(300);
      if (error || !active) return;
      const rows = ((data ?? []) as any[])
        .filter((row) => localTask.organization_id ? row.organization_id === localTask.organization_id : !row.organization_id && row.account_owner_id === localTask.owner_id)
        .map((row) => ({ id: String(row.id), code: row.code, name: row.name || row.code || `Departamento ${row.id}` }));
      const current = department ? { id: String(department.id), code: department.code, name: department.name || department.code || "Departamento actual" } : null;
      const merged = current && !rows.some((row) => row.id === current.id) ? [current, ...rows] : rows;
      setDepartmentOptions(merged);
    }
    void loadDepartments();
    return () => { active = false; };
  }, [canEdit, department, supabase, localTask.organization_id, localTask.owner_id]);
  const isEditing = mode === "edit" && canEdit; const done = checklistItems.filter((item) => Boolean(item.done)).length; const progress = checklistItems.length ? Math.round((done / checklistItems.length) * 100) : 0;
  const mainAssignee = assignees[0]?.profiles?.full_name || assignees[0]?.profiles?.email || assignableUsers[0]?.full_name || assignableUsers[0]?.email || "Sin responsable"; const startDate = localTask.created_at ? formatDate(localTask.created_at) : "No indicada"; const dueDate = form.dueDate ? formatDate(form.dueDate) : "Sin fecha límite";
  function enterEditMode() { if (!canEdit) return; setShareState("idle"); setMode("edit"); }
  function cancelEdit() { setForm(initialForm); setSaveState("saved"); setMode("read"); }
  async function copyTaskLink() { setShareState("idle"); try { const taskUrl = typeof window !== "undefined" ? window.location.href.split("?")[0] : `/app/tasks/${task.id}`; await navigator.clipboard.writeText(taskUrl); setShareState("copied"); window.setTimeout(() => setShareState("idle"), 2200); } catch { setShareState("error"); window.setTimeout(() => setShareState("idle"), 2200); } }
  function showNotice(message: string, tone: "success" | "error" | "info" = "info") { setNotice({ message, tone }); window.setTimeout(() => setNotice(null), 3600); }
  async function deleteCurrentTask() { if (!canEdit) return; setSaveState("saving"); const result = await safeDeleteTaskClient(supabase as any, task.id); setSaveState("saved"); setConfirmDeleteOpen(false); if (!result.ok) { showNotice(result.error ?? "No se pudo eliminar la tarea.", "error"); return; } showNotice(result.fallback ? "Tarea eliminada. Aplica la migración 0052 para activar papelera segura." : "Tarea enviada a papelera.", "success"); router.replace(`/app/tasks${queryString ? `?${queryString}` : ""}`); router.refresh(); }

  async function saveInline() { if (!canEdit) return; setSaveState("saving"); const payload = { title: form.title.trim(), description: form.description.trim() || null, status: form.status, priority: form.priority, due_date: form.dueDate || null, client_name: form.clientName.trim() || null, department_id: form.departmentId ? Number(form.departmentId) : null }; const { data, error } = await supabase.from("tasks").update(payload).eq("id", task.id).select("id,title,description,status,priority,due_date,client_name,department_id,updated_at,created_at,organization_id,owner_id").maybeSingle(); if (error || !data) { console.error("[task-workspace-inline] save failed", getMutationErrorMessage(error, "No Supabase row returned for task update.")); setSaveState("error"); return; } await logActivity(supabase, { entityType: "task", entityId: task.id, action: "task_updated", metadata: { title: data.title, status: data.status, priority: data.priority, due_date: data.due_date, department_id: data.department_id, confirmed_at: data.updated_at } }); setSaveState("saved"); setLocalTask((current: any) => ({ ...current, ...data })); setForm((current) => ({ ...current, title: data.title ?? current.title, description: data.description ?? "", status: data.status ?? current.status, priority: data.priority ?? current.priority, dueDate: data.due_date ?? "", clientName: data.client_name ?? "", departmentId: data.department_id ? String(data.department_id) : "" })); setMode("read"); showNotice("Tarea actualizada.", "success"); startTransition(() => router.refresh()); }

  return <div data-editing={isEditing ? "true" : "false"} className="min-h-screen bg-[#F7F9FC] ft-text-main"><div className="mx-auto max-w-[1440px] px-3.5 py-3 sm:px-5 lg:px-6"><div className="mb-3 flex items-center justify-between gap-2.5"><Link href={`/app/tasks${queryString ? `?${queryString}` : ""}`} className="ft-arrow-action text-[13px] font-semibold ft-text-muted hover:ft-text-main"><ArrowLeft className="h-4 w-4" /> Volver a tareas</Link><div className="hidden lg:flex"><SaveStateBadge state={saveState} /></div></div>
    {notice ? <div className={`mb-3 rounded-2xl border px-4 py-3 text-sm font-semibold ${notice.tone === "error" ? "border-rose-200 bg-rose-50 text-rose-700" : notice.tone === "success" ? "border-emerald-200 bg-emerald-50 text-emerald-700" : "border-slate-200 bg-slate-50 text-slate-700"}`}><span className="inline-flex items-center gap-2">{notice.tone === "error" ? <AlertCircle className="h-4 w-4" /> : <CheckCircle2 className="h-4 w-4" />}{notice.message}</span></div> : null}
    {confirmDeleteOpen ? <div className="mb-3 rounded-2xl border border-rose-200 bg-rose-50 p-4 text-rose-900"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><p className="text-sm font-bold">¿Deseas eliminar esta tarea?</p><p className="mt-1 text-xs font-semibold text-rose-700">Esta acción no se puede deshacer.</p></div><div className="flex gap-2"><button type="button" onClick={() => setConfirmDeleteOpen(false)} className="h-10 rounded-xl border border-[#E2E8F0] bg-white px-4 text-sm font-semibold text-slate-700">Cancelar</button><button type="button" onClick={() => void deleteCurrentTask()} className="inline-flex h-10 items-center gap-2 rounded-xl bg-rose-600 px-4 text-sm font-semibold text-white hover:bg-rose-700"><Trash2 className="h-4 w-4" />Eliminar</button></div></div></div> : null}
    <div className="grid grid-cols-1 gap-5 xl:grid-cols-[minmax(0,1fr)_360px]"><main className="min-w-0 space-y-5"><header className="border-b border-[#E2E8F0] pb-6"><div className="flex flex-wrap items-center gap-3 text-sm"><span className="inline-flex items-center gap-2 font-semibold text-[#10B981]"><span className="h-2.5 w-2.5 rounded-full bg-[#10B981]" />{humanStatus(form.status)}</span><span className="text-[#CBD5E1]">•</span><span className="inline-flex items-center gap-2 font-semibold"><Flag className="h-4 w-4 text-[#F59E0B]" />{priorityLabel(form.priority)}</span><span className="text-[#CBD5E1]">•</span><ProgressInline value={progress} /></div>
      <div className="mt-5 flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div className="min-w-0 flex-1">{isEditing ? <input autoFocus value={form.title} onChange={(event) => setForm((current) => ({ ...current, title: event.target.value }))} className="w-full rounded-xl border border-[#16C784]/40 bg-white px-3 py-2 text-[28px] font-semibold leading-tight tracking-[-0.035em] outline-none ring-4 ring-[#16C784]/10 sm:text-[28px]" placeholder="Escribe el título de la tarea…" /> : <h1 onDoubleClick={enterEditMode} className="text-[24px] font-semibold leading-tight tracking-[-0.028em] sm:text-[28px]">{form.title || "Sin título"}</h1>}</div><div className="flex shrink-0 items-center gap-2"><button type="button" onClick={copyTaskLink} className="inline-flex h-10 items-center gap-2 rounded-xl border border-[#E2E8F0] bg-white px-3.5 text-[13px] font-semibold ft-text-main transition hover:bg-[#F8FAFC]"><Share2 className="h-4 w-4" /> {shareState === "copied" ? "Copiado" : shareState === "error" ? "No copiado" : "Compartir"}</button>{canEdit ? <button type="button" onClick={() => setConfirmDeleteOpen(true)} className="inline-flex h-10 items-center gap-2 rounded-xl border border-rose-200 bg-rose-50 px-3.5 text-[13px] font-semibold text-rose-700 transition hover:bg-rose-100"><Trash2 className="h-4 w-4" />Eliminar</button> : null}{isEditing ? <button type="button" onClick={cancelEdit} className="h-11 rounded-xl border border-[#E2E8F0] bg-white px-3.5 text-[13px] font-semibold hover:bg-[#F8FAFC]">Cancelar</button> : null}{canEdit ? <button type="button" onClick={isEditing ? saveInline : enterEditMode} className="h-11 rounded-xl bg-[#16C784] px-4 text-[13px] font-semibold text-white hover:bg-[#13B376]">{isEditing ? "Guardar" : "Editar"}</button> : null}</div></div>
      <div className="mt-4 flex flex-wrap gap-2"><MetaChip><Folder className="h-3.5 w-3.5" />{project?.title || "Tarea independiente"}</MetaChip><MetaChip>{department?.name || "Sin departamento"}</MetaChip><MetaChip><span className="grid h-5 w-5 place-items-center rounded-full bg-[#EFF6FF] text-[10px] font-semibold text-[#3B82F6]">{initials(form.clientName || mainAssignee).slice(0, 2)}</span>{form.clientName || mainAssignee}</MetaChip></div></header>
      <section className="group rounded-2xl border border-transparent p-1 transition hover:border-[#E2E8F0]"><div className="mb-2 flex items-center justify-between"><h2 className="text-sm font-semibold">Descripción</h2>{!isEditing && canEdit ? <button type="button" onClick={enterEditMode} className="text-sm font-semibold ft-text-muted opacity-0 transition group-hover:opacity-100">Editar</button> : null}</div>{isEditing ? <div className="overflow-hidden rounded-2xl border border-[#E2E8F0] bg-white"><div className="flex items-center gap-4 border-b border-[#EEF2F7] bg-[#F8FAFC] px-4 py-3 text-sm font-bold text-[#94A3B8]"><span>B</span><span>I</span><span>≡</span><Paperclip className="h-4 w-4" /></div><textarea value={form.description} onChange={(event) => setForm((current) => ({ ...current, description: event.target.value }))} className="min-h-[132px] w-full resize-y bg-white p-4 text-base leading-7 outline-none" placeholder="Describe contexto, entregables o notas importantes…" /></div> : <p onDoubleClick={enterEditMode} className="text-base leading-7">{form.description || "Sin descripción."}</p>}</section>
      <TaskChecklistCard taskId={task.id} initialItems={checklistItems} canManage={access.canEdit || access.isAssignee} />{checklistItems.length === 0 ? <div className="rounded-2xl border border-[#FDE68A] bg-[#FFF8E8] p-4 text-sm font-semibold text-[#92400E]"><div className="flex gap-3"><Sparkles className="mt-0.5 h-5 w-5 shrink-0" /><p><strong>Checklist recomendado:</strong> esta tarea inicia en 0%. Agrega el primer paso para que el progreso sea real y sincronizado.</p></div></div> : null}
      <TaskOperationalFeed taskId={task.id} comments={comments as any[]} activity={activity as any[]} canComment={access.canComment} activityLabel={activityLabel} />
      <section id="attachments" className="rounded-2xl border border-[#E2E8F0] bg-white p-5"><EntityAttachments entityType="task" entityId={task.id} attachments={attachments} canManage={access.canUploadAttachments} variant="list" /></section></main>
      <aside className="space-y-4 xl:sticky xl:top-24 xl:self-start"><SidePanel title="Información">{isEditing ? <><InlineMeta label="Estado"><select value={form.status} onChange={(event) => setForm((current) => ({ ...current, status: event.target.value }))} className="h-10 w-full rounded-xl border border-[#E2E8F0] bg-white px-3 text-sm outline-none focus:border-[#16C784] focus:ring-4 focus:ring-[#16C784]/10">{statusOptions.map((status) => <option key={status} value={status}>{humanStatus(status)}</option>)}</select></InlineMeta><InlineMeta label="Prioridad"><select value={form.priority} onChange={(event) => setForm((current) => ({ ...current, priority: event.target.value }))} className="h-10 w-full rounded-xl border border-[#E2E8F0] bg-white px-3 text-sm outline-none focus:border-[#16C784] focus:ring-4 focus:ring-[#16C784]/10">{priorityOptions.map((priority) => <option key={priority} value={priority}>{priorityLabel(priority)}</option>)}</select></InlineMeta></> : null}<InlineMeta label="Proyecto">{project?.title || "Tarea independiente"}</InlineMeta><InlineMeta label="Cliente">{isEditing ? <input value={form.clientName} onChange={(event) => setForm((current) => ({ ...current, clientName: event.target.value }))} className="h-10 w-full rounded-xl border border-[#E2E8F0] bg-white px-3 text-sm outline-none focus:border-[#16C784] focus:ring-4 focus:ring-[#16C784]/10" /> : form.clientName || "No indicado"}</InlineMeta><InlineMeta label="Departamento">{isEditing ? <select value={form.departmentId} onChange={(event) => setForm((current) => ({ ...current, departmentId: event.target.value }))} className="h-10 w-full rounded-xl border border-[#E2E8F0] bg-white px-3 text-sm outline-none focus:border-[#16C784] focus:ring-4 focus:ring-[#16C784]/10"><option value="">Sin departamento</option>{departmentOptions.map((option) => <option key={option.id} value={option.id}>{option.name}</option>)}</select> : (departmentOptions.find((option) => option.id === form.departmentId)?.name || department?.name || "No indicado")}</InlineMeta></SidePanel>
        <SidePanel title="Responsables">{(assignees.length ? assignees : [{ id: "fallback", profiles: { full_name: mainAssignee } }]).slice(0, 4).map((item: any) => { const profile = Array.isArray(item.profiles) ? item.profiles[0] : item.profiles; const name = profile?.full_name || profile?.email || mainAssignee; return <div key={item.id ?? name} className="flex items-center justify-between gap-3 text-sm"><span className="inline-flex min-w-0 items-center gap-3 font-semibold"><span className="grid h-8 w-8 place-items-center rounded-full bg-[#16C784] text-xs text-white">{initials(name)}</span><span className="truncate">{name}</span></span><span className="text-xs font-semibold ft-text-muted">Responsable</span></div>; })}{canEdit ? <p className="rounded-xl bg-[#F8FAFC] p-3 text-xs font-semibold ft-text-muted">La edición de responsables se mantiene en el módulo de permisos/asignaciones para evitar cambios accidentales.</p> : null}</SidePanel>
        <SidePanel title="Fechas"><InlineMeta label="Inicio"><span className="inline-flex items-center gap-2">{startDate}<CalendarDays className="h-4 w-4 ft-text-muted" /></span></InlineMeta><InlineMeta label="Límite">{isEditing ? <input type="date" value={form.dueDate || ""} onChange={(event) => setForm((current) => ({ ...current, dueDate: event.target.value }))} className="h-10 w-full rounded-xl border border-[#E2E8F0] bg-white px-3 text-sm outline-none focus:border-[#16C784] focus:ring-4 focus:ring-[#16C784]/10" /> : <span className={`inline-flex items-center gap-2 ${taskIsOverdue ? "text-rose-600" : ""}`}>{dueDate}<CalendarDays className="h-4 w-4" /></span>}</InlineMeta><InlineMeta label="Recordatorio"><span className="inline-flex items-center gap-2">1 día antes <Bell className="h-4 w-4 ft-text-muted" /></span></InlineMeta>{standbyDays ? <p className="rounded-xl bg-[#FFF8E8] p-3 text-sm font-bold text-[#92400E]">En espera desde hace {standbyDays} día{standbyDays === 1 ? "" : "s"}.</p> : null}</SidePanel>
        <SidePanel title="Adjuntos"><div className="grid grid-cols-3 gap-3">{attachments.slice(0, 2).map((file: any) => <a key={file.id} href={file.public_url || "#attachments"} className="group min-w-0" target={file.public_url ? "_blank" : undefined} rel="noreferrer"><span className="grid aspect-square place-items-center overflow-hidden rounded-xl border border-[#E2E8F0] bg-[#F8FAFC] text-xs font-semibold ft-text-muted group-hover:bg-white">{file.public_url && (file.mime_type || "").startsWith("image/") ? <img src={file.public_url} alt={file.file_name || "Adjunto"} className="h-full w-full object-cover" /> : <AttachmentPreviewIcon file={file} />}</span><span className="mt-2 block truncate text-[11px] font-semibold text-[#475569]">{file.file_name}</span></a>)}<a href="#attachments" className="grid aspect-square place-items-center rounded-xl border border-dashed border-[#CBD5E1] bg-[#F8FAFC] ft-text-muted hover:bg-white"><Plus className="h-5 w-5" /></a></div><a href="#attachments" className="block text-sm font-semibold text-[#2563EB]">Ver todos los archivos ({attachments.length})</a></SidePanel></aside></div></div></div>;
}
