#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
const root = process.cwd();
const failures = [];
const read = (rel) => fs.existsSync(path.join(root, rel)) ? fs.readFileSync(path.join(root, rel), "utf8") : "";
const exists = (rel) => fs.existsSync(path.join(root, rel));
const requireIncludes = (rel, text) => { if (!read(rel).includes(text)) failures.push(`Expected '${text}' in ${rel}`); };
const pkg = JSON.parse(read("package.json"));
if (pkg.version !== "58.24.6-boards-home-ui-redesign-saved-board-delete") failures.push("package version must be v58.24.6 boards home redesign");
if ((pkg.scripts ?? {})["verify:current"] !== "npm run verify:v58.24.6") failures.push("verify:current must target verify:v58.24.6");
if ((pkg.scripts ?? {})["verify:v58.24.6"] !== "node scripts/verify-v58.24.6.mjs") failures.push("verify:v58.24.6 script must be available");
if (!exists("scripts/verify-v58.24.6.mjs")) failures.push("missing verify-v58.24.6 script");
requireIncludes("src/lib/release/version.ts", "58.24.6-boards-home-ui-redesign-saved-board-delete");
requireIncludes("src/lib/release/version.ts", "v58.24.6 Boards Home UI Redesign + Saved Board Delete");
requireIncludes("package-lock.json", "58.24.6-boards-home-ui-redesign-saved-board-delete");
requireIncludes("src/components/boards/boards-home.tsx", "board-home-hero");
requireIncludes("src/components/boards/boards-home.tsx", "HeroIllustration");
requireIncludes("src/components/boards/boards-home.tsx", "board-home-template-card");
requireIncludes("src/components/boards/boards-home.tsx", "board-home-recent-card");
requireIncludes("src/components/boards/boards-home.tsx", "board-home-delete-btn");
requireIncludes("src/components/boards/boards-home.tsx", "deleteBoard");
requireIncludes("src/components/boards/boards-home.tsx", "deleted_at");
requireIncludes("src/components/boards/boards-home.tsx", "board-home-delete-dialog");
requireIncludes("src/app/globals.css", "v58.24.6 — Boards Home UI Redesign + Saved Board Delete");
requireIncludes("src/app/globals.css", ".board-home-shell");
requireIncludes("src/app/globals.css", ".board-home-hero");
requireIncludes("src/app/globals.css", ".board-home-template-grid");
requireIncludes("src/app/globals.css", ".board-home-recent-grid");
requireIncludes("src/app/globals.css", ".board-home-delete-dialog");
requireIncludes("docs/release/V58_24_6_BOARDS_HOME_UI_REDESIGN_SAVED_BOARD_DELETE.md", "v58.24.6");
requireIncludes("docs/qa/FLOWTASK_V58_24_6_BOARDS_HOME_QA.md", "QA");
if (failures.length) { console.error("[verify:v58.24.6] FAIL"); for (const f of failures) console.error(`- ${f}`); process.exit(1); }
console.log("[verify:v58.24.6] OK — Boards home redesign and saved board delete aligned.");
