#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
const root = process.cwd();
const failures = [];
const read = (rel) => fs.existsSync(path.join(root, rel)) ? fs.readFileSync(path.join(root, rel), "utf8") : "";
const exists = (rel) => fs.existsSync(path.join(root, rel));
const requireIncludes = (rel, text) => { if (!read(rel).includes(text)) failures.push(`Expected '${text}' in ${rel}`); };
const requireNotIncludes = (rel, text) => { if (read(rel).includes(text)) failures.push(`Unexpected '${text}' in ${rel}`); };
const pkg = JSON.parse(read("package.json"));
if (pkg.version !== "58.24.3-board-visual-polish-toolbar-system-hardening") failures.push("package version must be v58.24.3 visual polish");
if ((pkg.scripts ?? {})["verify:current"] !== "npm run verify:v58.24.3") failures.push("verify:current must target verify:v58.24.3");
if ((pkg.scripts ?? {})["verify:v58.24.3"] !== "node scripts/verify-v58.24.3.mjs") failures.push("verify:v58.24.3 script must be available");
if (!exists("scripts/verify-v58.24.3.mjs")) failures.push("missing verify-v58.24.3 script");
requireIncludes("src/lib/release/version.ts", "58.24.3-board-visual-polish-toolbar-system-hardening");
requireIncludes("src/lib/release/version.ts", "v58.24.3 Board Visual Polish + Toolbar System Hardening");
requireIncludes("src/components/boards/board-toolbox.tsx", "flowtask.board.toolbar.v58.24.3");
requireIncludes("src/components/boards/board-toolbox.tsx", "board-tool-palette-header");
requireIncludes("src/components/boards/board-toolbox.tsx", "board-tool-drag-handle");
requireIncludes("src/components/boards/board-toolbox.tsx", "board-tool-floating-trigger");
requireIncludes("src/components/boards/board-page.tsx", "board-clear-cancel");
requireIncludes("src/components/boards/board-page.tsx", "board-clear-danger");
requireIncludes("src/app/globals.css", "v58.24.3 — Board Visual Polish");
requireIncludes("src/app/globals.css", ".board-clear-cancel");
requireIncludes("src/app/globals.css", ".board-clear-danger");
requireIncludes("src/app/globals.css", ".board-tool-palette-title");
requireIncludes("src/app/globals.css", "width: 154px");
requireIncludes("src/components/boards/properties-panel.tsx", "Stepper");
requireNotIncludes("src/components/boards/properties-panel.tsx", "> Fila</button>");
requireNotIncludes("src/components/boards/properties-panel.tsx", "> Columna</button>");
requireNotIncludes("src/components/boards/board-page.tsx", "<BoardWorkspaceRail");
if (failures.length) { console.error("[verify:v58.24.3] FAIL"); for (const f of failures) console.error(`- ${f}`); process.exit(1); }
console.log("[verify:v58.24.3] OK — Board visual polish and toolbar system hardening aligned.");
