#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
const root = process.cwd();
const failures = [];
const read = (rel) => fs.existsSync(path.join(root, rel)) ? fs.readFileSync(path.join(root, rel), "utf8") : "";
const exists = (rel) => fs.existsSync(path.join(root, rel));
const requireIncludes = (rel, text) => { if (!read(rel).includes(text)) failures.push(`Expected '${text}' in ${rel}`); };
const requireNotIncludes = (rel, text) => { if (read(rel).includes(text)) failures.push(`Unexpected '${text}' in ${rel}`); };
const pkg = JSON.parse(read("package.json"));
if (pkg.version !== "58.24.5-board-toolbar-collapse-animation-fix") failures.push("package version must be v58.24.5 toolbar collapse animation fix");
if ((pkg.scripts ?? {})["verify:current"] !== "npm run verify:v58.24.5") failures.push("verify:current must target verify:v58.24.5");
if ((pkg.scripts ?? {})["verify:v58.24.5"] !== "node scripts/verify-v58.24.5.mjs") failures.push("verify:v58.24.5 script must be available");
if (!exists("scripts/verify-v58.24.5.mjs")) failures.push("missing verify-v58.24.5 script");
requireIncludes("src/lib/release/version.ts", "58.24.5-board-toolbar-collapse-animation-fix");
requireIncludes("src/lib/release/version.ts", "v58.24.5 Board Toolbar Collapse Animation Fix");
requireIncludes("package-lock.json", "58.24.5-board-toolbar-collapse-animation-fix");
requireIncludes("src/components/boards/board-toolbox.tsx", "flowtask.board.toolbar.v58.24.5");
requireIncludes("src/components/boards/board-toolbox.tsx", "changeMode");
requireIncludes("src/components/boards/board-toolbox.tsx", "board-tool-collapse-hide");
requireIncludes("src/components/boards/board-toolbox.tsx", "board-tooltip");
requireIncludes("src/components/boards/board-toolbox.tsx", "board-tool-label");
requireIncludes("src/components/boards/board-topbar.tsx", "board-topbar");
requireIncludes("src/components/boards/board-topbar.tsx", "board-present-button");
requireIncludes("src/components/boards/board-topbar.tsx", "board-share-button");
requireIncludes("src/components/boards/board-page.tsx", "board-shell");
requireIncludes("src/components/boards/board-page.tsx", "board-editor-main");
requireIncludes("src/components/boards/board-page.tsx", "board-zoom-controls");
requireIncludes("src/components/boards/properties-panel.tsx", "board-inspector");
requireIncludes("src/components/boards/properties-panel.tsx", "board-input");
requireIncludes("src/components/boards/board-element.tsx", "board-selection-ring");
requireIncludes("src/app/globals.css", "v58.24.5 — Board Toolbar Collapse Animation Fix");
requireIncludes("src/app/globals.css", ".board-tool-collapse-hide");
requireIncludes("src/app/globals.css", ".board-tool-palette-collapsed .board-tool-palette-header");
requireIncludes("src/app/globals.css", ".board-topbar");
requireIncludes("src/app/globals.css", ".board-tooltip");
requireIncludes("src/app/globals.css", ".board-selection-ring");
requireIncludes("docs/release/V58_24_5_BOARD_TOOLBAR_COLLAPSE_ANIMATION_FIX.md", "v58.24.5");
requireIncludes("docs/qa/FLOWTASK_V58_24_5_BOARD_TOOLBAR_COLLAPSE_QA.md", "QA");
requireIncludes("docs/boards/FLOWTASK_BOARD_PREMIUM_VISUAL_SYSTEM.md", "board-shell");
requireNotIncludes("src/components/boards/board-page.tsx", "<BoardWorkspaceRail");
if (failures.length) { console.error("[verify:v58.24.5] FAIL"); for (const f of failures) console.error(`- ${f}`); process.exit(1); }
console.log("[verify:v58.24.5] OK — Board toolbar collapse animation fix aligned.");
