#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
const root = process.cwd();
const failures = [];
const read = (rel) => fs.existsSync(path.join(root, rel)) ? fs.readFileSync(path.join(root, rel), "utf8") : "";
const exists = (rel) => fs.existsSync(path.join(root, rel));
const requireIncludes = (rel, text) => { if (!read(rel).includes(text)) failures.push(`Expected '${text}' in ${rel}`); };
const requireNotIncludes = (rel, text) => { if (read(rel).includes(text)) failures.push(`Unexpected '${text}' in ${rel}`); };
const pkg = JSON.parse(read("package.json"));
if (pkg.version !== "58.24.1-board-editor-ux-element-controls-hardening") failures.push("package version must be v58.24.1 hardening");
if ((pkg.scripts ?? {})["verify:current"] !== "npm run verify:v58.24.1") failures.push("verify:current must target verify:v58.24.1");
if (!exists("scripts/verify-v58.24.1.mjs")) failures.push("missing verify-v58.24.1 script");
requireIncludes("src/lib/release/version.ts", "58.24.1-board-editor-ux-element-controls-hardening");
requireIncludes("src/components/boards/board-toolbox.tsx", "board-tool-palette");
requireIncludes("src/components/boards/board-toolbox.tsx", "Tipo de forma");
requireIncludes("src/components/boards/board-page.tsx", "handleResizeStart");
requireIncludes("src/components/boards/board-page.tsx", "handleConnectorPointDragStart");
requireIncludes("src/components/boards/board-page.tsx", "handleCommentDragStart");
requireIncludes("src/components/boards/properties-panel.tsx", "Posición y tamaño");
requireIncludes("src/components/boards/properties-panel.tsx", "Stepper");
requireIncludes("src/components/boards/properties-panel.tsx", "Tipo de forma");
requireIncludes("src/components/boards/board-comments-activity.tsx", "onUpdateComment");
requireIncludes("src/components/boards/board-comments-activity.tsx", "onResolveComment");
requireIncludes("src/components/boards/board-comments-activity.tsx", "onDeleteComment");
requireIncludes("src/components/boards/connector-layer.tsx", "onConnectorPointDragStart");
requireIncludes("src/app/globals.css", ".board-tool-palette");
requireNotIncludes("src/components/boards/board-page.tsx", "<BoardWorkspaceRail");
requireNotIncludes("src/components/boards/board-page.tsx", "lg:grid-cols-[76px_1fr]");
if (failures.length) { console.error("[verify:v58.24.1] FAIL"); for (const f of failures) console.error(`- ${f}`); process.exit(1); }
console.log("[verify:v58.24.1] OK — Board editor UX and element controls hardening aligned.");
